### PR TITLE
feat: report metadata when loaded

### PR DESCRIPTION
**Pull request by slowmove**

### CODE REVIEW

**Comment by birme** [comment]
I suppose we should update the EPAS implementation in the web-component as dröm?

**Comment by birme** [comment]
Nothing is needed in the ShakaTech ?

**Comment by slowmove** [comment]
> Nothing is needed in the ShakaTech ?

It works good enough with the standard loaded event in base tech, as it seems.

**Review by birme — APPROVED** [review]

**Review by Sellebr8n — APPROVED** [review]
LGTM!

**Pull request merged**
